services:
  - docker:18.09.7-dind

default:
  image: docker:stable
  tags:
    - dsp

.test: &test
  stage: build
  image: maven:3.6-jdk-11
  script:
    - infra/scripts/test-end-to-end.sh
  except:
    - ^v0\.(3|4)-branch$

variables:
  DOCKER_HOST: tcp://localhost:2375
  # This is the region of AWS, used by the deployer ecs-deploy
  REGION: "eu-west-1"
  ACCOUNT: "674300753731"
  SERVICE_NAME: "feast"
  # Image name
  IMAGE_NAME: "feast"
  # Elastic Container Registry URL of the package.
  ECR_URL: "674300753731.dkr.ecr.eu-west-1.amazonaws.com/feast"
  IMAGE_TAG: "0.6.${CI_PIPELINE_IID}"

before_script:
  - | # ${variable//-/} is a bash replacement that strips the hyphens from the contents of the variable. Needed for API Gateway.
    echo "===== Account => ${ACCOUNT}, Region => ${REGION} ====="
    apt-get install curl jq python3 py-pip
    pip3 install awscli
    echo $(python3 --version)
    echo $(pip3 --version)
    $(aws ecr get-login --no-include-email --region ${REGION}  --registry-ids ${ACCOUNT})

stages:
  # - build
  - publish

test:
  <<: *test

"build & publish":
  stage: publish
  when: manual
  script:
    - |
      infra/scripts/download-maven-cache.sh \
        --archive-uri gs://feast-templocation-kf-feast/.m2.2020-07-13.tar \
        --output-dir $PWD/

      infra/scripts/publish-docker-image.sh \
        --repository ${ECR_URL}/feast-core \
        --tag ${IMAGE_TAG} \
        --file infra/docker/core/Dockerfile

      infra/scripts/publish-docker-image.sh \
        --repository ${ECR_URL}/feast-serving \
        --tag ${IMAGE_TAG} \
        --file infra/docker/serving/Dockerfile
