FROM openjdk:11-jre
ARG REVISION=dev
ADD $PWD/core/target/feast-core-$REVISION.jar /Repository/feast-core.jar
CMD ["java",\
     "-Xms2048m",\
     "-Xmx2048m",\
     "-jar",\
     "/Repository/feast-core.jar"]